<?php 

/* rocks.module */
function rocks_menu(){
	// urls

 $items['rocks/form'] = array(
      'page callback' => 'pageform',
      'page arguments' => array(),
      'access arguments' => array('access content'),
      'file' => 'lib/rocks_form.inc',
    ); 

    $items['rocks/index'] = array(
      'page callback' => 'pagething',
      'page arguments' => array(),
      'access arguments' => array('access content'),
      //'type' => MENU_NORMAL,
    ); 
    return $items;
}

function pageform(){
  return drupal_get_form('rocks_firstform');
}

function pagething(){
	return theme('yoyoyo');
}

//register theme
function rocks_theme(){


 $themes = array (
        'yoyoyo' => array(
            'template' => 'page-rocks', // your template file called page-rocks.tpl.php
            'arguments' => array(),
        ),
    );
    return $themes;

	
}